[package]
name = "hyprcut"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hyprcut"
path = "src/main.rs"

[dependencies]
gtk4 = { version = "0.11", features = ["v4_10"] }
gtk4-layer-shell = { version = "0.8" }
gdk4 = "0.11"
glib = "0.22"
hyprland = "0.4.0-beta.3"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
notify-debouncer-mini = "0.7"
anyhow = "1"
